spring:
  application:
    name: Tennis Club Reservation System

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tennis
    username: user
    password: password
  liquibase:
    enabled: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate

server:
  servlet:
    context-path: "/api"

database:
  seed: true

jwt:
  secret: mySuperLongSecretKeyValueThatHasAtLeastThirtyTwoCharacters
  expiration: 900000
